#!/usr/bin/env python3
#
# Dumps the ROM files listed in a manifest into a C header, as one array per
# ROM. This replaces the fips "dump" code generator that was dropped along with
# sokol.
#
# Usage:
#   dump.py <manifest> <output header>   generate the header
#   dump.py --list <manifest>            print the ROM paths, one per line

import os
import re
import sys

BYTES_PER_LINE = 16


def read_manifest(path):
    """Returns the ROM paths listed under the "files" key of the manifest.

    The manifest is a trivial YAML list, so it's parsed by hand to avoid a
    dependency on PyYAML.
    """
    files = []
    in_files = False

    with open(path) as f:
        for line in f:
            line = line.rstrip("\n")

            if not line.strip() or line.strip() == "---":
                continue

            item = re.match(r"^\s+-\s+(\S+)\s*$", line)

            if in_files and item:
                files.append(item.group(1))
            elif line.strip() == "files:":
                in_files = True
            elif not line.startswith((" ", "\t")):
                in_files = False

    if not files:
        sys.exit("{}: no files listed".format(path))

    return [os.path.join(os.path.dirname(path), file) for file in files]


def symbol_name(path):
    """Returns the C identifier for a ROM file, e.g. "5.5p" -> "dump_5"."""
    stem = os.path.splitext(os.path.basename(path))[0]
    return "dump_{}".format(re.sub(r"[^0-9A-Za-z_]", "_", stem))


def write_array(out, path):
    with open(path, "rb") as f:
        data = f.read()

    out.write("static const uint8_t {}[{}] = {{\n".format(symbol_name(path),
                                                          len(data)))

    for offset in range(0, len(data), BYTES_PER_LINE):
        chunk = data[offset:offset + BYTES_PER_LINE]
        out.write("  " + " ".join("0x{:02x},".format(byte) for byte in chunk) + "\n")

    out.write("};\n")


def generate(manifest, out_path):
    files = read_manifest(manifest)

    for file in files:
        if not os.path.isfile(file):
            sys.exit("{}: input file not found".format(file))

    with open(out_path, "w") as out:
        out.write("#pragma once\n\n")
        out.write("/* machine generated by tools/dump.py, do not edit! */\n\n")
        out.write("#include <stdint.h>\n")

        for file in files:
            out.write("\n")
            write_array(out, file)


def main(argv):
    if len(argv) == 3 and argv[1] == "--list":
        print("\n".join(read_manifest(argv[2])))
    elif len(argv) == 3:
        generate(argv[1], argv[2])
    else:
        sys.exit("usage: dump.py [--list] <manifest> [output header]")


if __name__ == "__main__":
    main(sys.argv)
